import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'jsdom',
    include: ['src/app/features/algorithms/**/*.spec.ts'],
    restoreMocks: true,
    clearMocks: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      reportsDirectory: './coverage/algorithms',
      include: [
        'src/app/features/algorithms/algorithm-card/algorithm-card.utils/**/*.ts',
        'src/app/features/algorithms/algorithm-card/algorithm-card-preview/algorithm-card-preview-spec/**/*.ts',
        'src/app/features/algorithms/algorithm-detail/algorithm-detail-config/**/*.ts',
        'src/app/features/algorithms/algorithm-traits/**/*.ts',
        'src/app/features/algorithms/algorithms-page/algorithms-page.utils/**/*.ts',
        'src/app/features/algorithms/algorithms/a-star-pathfinding/**/*.ts',
        'src/app/features/algorithms/algorithms/bellman-ford/**/*.ts',
        'src/app/features/algorithms/algorithms/climbing-stairs/**/*.ts',
        'src/app/features/algorithms/algorithms/coin-change/**/*.ts',
        'src/app/features/algorithms/algorithms/bfs/**/*.ts',
        'src/app/features/algorithms/algorithms/bipartite-check/**/*.ts',
        'src/app/features/algorithms/algorithms/burrows-wheeler-transform/**/*.ts',
        'src/app/features/algorithms/algorithms/connected-components/**/*.ts',
        'src/app/features/algorithms/algorithms/cycle-detection/**/*.ts',
        'src/app/features/algorithms/algorithms/dfs/**/*.ts',
        'src/app/features/algorithms/algorithms/dijkstra/**/*.ts',
        'src/app/features/algorithms/algorithms/edit-distance/**/*.ts',
        'src/app/features/algorithms/algorithms/fibonacci-dp/**/*.ts',
        'src/app/features/algorithms/algorithms/flood-fill/**/*.ts',
        'src/app/features/algorithms/algorithms/floyd-warshall/**/*.ts',
        'src/app/features/algorithms/algorithms/burst-balloons/**/*.ts',
        'src/app/features/algorithms/algorithms/binary-search/**/*.ts',
        'src/app/features/algorithms/algorithms/binary-search-variants/**/*.ts',
        'src/app/features/algorithms/algorithms/huffman-coding/**/*.ts',
        'src/app/features/algorithms/algorithms/knapsack-01/**/*.ts',
        'src/app/features/algorithms/algorithms/kmp-pattern-matching/**/*.ts',
        'src/app/features/algorithms/algorithms/linear-search/**/*.ts',
        'src/app/features/algorithms/algorithms/longest-increasing-subsequence/**/*.ts',
        'src/app/features/algorithms/algorithms/longest-common-subsequence/**/*.ts',
        'src/app/features/algorithms/algorithms/longest-palindromic-subsequence/**/*.ts',
        'src/app/features/algorithms/algorithms/manacher/**/*.ts',
        'src/app/features/algorithms/algorithms/matrix-chain-multiplication/**/*.ts',
        'src/app/features/algorithms/algorithms/rabin-karp/**/*.ts',
        'src/app/features/algorithms/algorithms/regex-matching-dp/**/*.ts',
        'src/app/features/algorithms/algorithms/run-length-encoding/**/*.ts',
        'src/app/features/algorithms/algorithms/subset-sum/**/*.ts',
        'src/app/features/algorithms/algorithms/topological-sort-kahn/**/*.ts',
        'src/app/features/algorithms/algorithms/wildcard-matching/**/*.ts',
        'src/app/features/algorithms/algorithms/z-algorithm/**/*.ts',
        'src/app/features/algorithms/components/code-panel/code-panel.dom/**/*.ts',
        'src/app/features/algorithms/components/code-panel/code-panel.utils/**/*.ts',
        'src/app/features/algorithms/components/string-visualization/string-visualization.utils/**/*.ts',
        'src/app/features/algorithms/data/**/*.ts',
        'src/app/features/algorithms/registry/algorithm-registry/**/*.ts',
        'src/app/features/algorithms/services/visualization-engine/**/*.ts',
        'src/app/features/algorithms/utils/**/*.ts',
      ],
      exclude: [
        '**/*.spec.ts',
      ],
      thresholds: {
        lines: 70,
        statements: 70,
      },
    },
  },
});
