import { marker as t } from '@jsverse/transloco-keys-manager/marker';

export const NOTEBOOK_TEXT = {
  sections: {
    augmented: t('features.algorithms.runtime.scratchpadLab.sections.augmented'),
    backElimination: t('features.algorithms.runtime.scratchpadLab.sections.backElimination'),
    check: t('features.algorithms.runtime.scratchpadLab.sections.check'),
    computation: t('features.algorithms.runtime.scratchpadLab.sections.computation'),
    conclusion: t('features.algorithms.runtime.scratchpadLab.sections.conclusion'),
    construction: t('features.algorithms.runtime.scratchpadLab.sections.construction'),
    coprimality: t('features.algorithms.runtime.scratchpadLab.sections.coprimality'),
    decomposition: t('features.algorithms.runtime.scratchpadLab.sections.decomposition'),
    factorisation: t('features.algorithms.runtime.scratchpadLab.sections.factorisation'),
    forwardElimination: t('features.algorithms.runtime.scratchpadLab.sections.forwardElimination'),
    initialTableau: t('features.algorithms.runtime.scratchpadLab.sections.initialTableau'),
    inverse: t('features.algorithms.runtime.scratchpadLab.sections.inverse'),
    iterations: t('features.algorithms.runtime.scratchpadLab.sections.iterations'),
    lastRemainder: t('features.algorithms.runtime.scratchpadLab.sections.lastRemainder'),
    model: t('features.algorithms.runtime.scratchpadLab.sections.model'),
    modulus: t('features.algorithms.runtime.scratchpadLab.sections.modulus'),
    optimality: t('features.algorithms.runtime.scratchpadLab.sections.optimality'),
    parameters: t('features.algorithms.runtime.scratchpadLab.sections.parameters'),
    pivot: t('features.algorithms.runtime.scratchpadLab.sections.pivot'),
    pointwise: t('features.algorithms.runtime.scratchpadLab.sections.pointwise'),
    probabilityCheck: t('features.algorithms.runtime.scratchpadLab.sections.probabilityCheck'),
    ratioTest: t('features.algorithms.runtime.scratchpadLab.sections.ratioTest'),
    result: t('features.algorithms.runtime.scratchpadLab.sections.result'),
    rootCheck: t('features.algorithms.runtime.scratchpadLab.sections.rootCheck'),
    run: t('features.algorithms.runtime.scratchpadLab.sections.run'),
    standardForm: t('features.algorithms.runtime.scratchpadLab.sections.standardForm'),
    sum: t('features.algorithms.runtime.scratchpadLab.sections.sum'),
    system: t('features.algorithms.runtime.scratchpadLab.sections.system'),
    transformA: t('features.algorithms.runtime.scratchpadLab.sections.transformA'),
    transformB: t('features.algorithms.runtime.scratchpadLab.sections.transformB'),
    baseTest: t('features.algorithms.runtime.scratchpadLab.sections.baseTest'),
    interpretation: t('features.algorithms.runtime.scratchpadLab.sections.interpretation'),
  },
  decisions: {
    note: t('features.algorithms.runtime.scratchpadLab.decisions.note'),
    compute: t('features.algorithms.runtime.scratchpadLab.decisions.compute'),
    result: t('features.algorithms.runtime.scratchpadLab.decisions.result'),
  },
} as const;
